# Generated by Django 3.0.5 on 2023-06-28 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_followinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followinglist',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
