# Generated by Django 3.0.5 on 2023-06-28 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230628_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followinglist',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='followinglist',
            unique_together={('from_user', 'to_user')},
        ),
    ]
